version: '3'
services:
  app:
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    user: root
    volumes:
      - .:/home/nodejs/wallet-api/
      - /home/nodejs/wallet-api/node_modules
    restart: on-failure
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 3
